import { useEffect, useMemo, useState } from 'react'
import { Pressable, Text, TextInput, View } from 'react-native'
import * as ImagePicker from 'expo-image-picker'
import { FoodResolver, LOCAL_FOOD_CATALOG, LocalFoodCatalogProvider, NutritionCalculator, buildMealParseContext, buildMealVisionContext, type FoodQueryDraft } from '@training/training-domain'
import type { LocalRepositories } from '@training/training-local-db'
import { AiGatewayClient, AI_PRIVACY_NOTICE } from '../ai/AiGatewayClient'
import { InlineNotice, SectionHeader } from '../../components/ui'
import { useTheme } from '../../theme'
import { createEmptyNutritionMealDraft, type NutritionMealDraft } from './models/nutritionDrafts'

const CONSENT_KEY = 'ai.free-tier-consent'
const ENABLED_KEY = 'ai.enabled'

export function AiMealAssistant({ date, repositories, onReview, action }: { date: string; repositories: LocalRepositories; onReview: (draft: NutritionMealDraft) => void; action: 'text' | 'image' }) {
  const { colors } = useTheme(); const client = useMemo(() => new AiGatewayClient(), []); const [enabled, setEnabled] = useState(false); const [available, setAvailable] = useState(false); const [text, setText] = useState(''); const [hint, setHint] = useState(''); const [image, setImage] = useState<{ base64: string; mimeType: 'image/jpeg' | 'image/png' | 'image/webp' } | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; void Promise.all([repositories.settings.get<boolean>(ENABLED_KEY), client.getStatus()]).then(([stored, status]) => { if (active) { setEnabled(stored === true); setAvailable(status.available) } }).catch(() => { if (active) setAvailable(false) }); return () => { active = false } }, [client, repositories])
  const accept = async () => { await repositories.settings.set(CONSENT_KEY, true); await repositories.settings.set(ENABLED_KEY, true); setEnabled(true) }
  const chooseImage = async (camera = false) => { setError(''); if (camera) { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) { setError('Permita acesso à câmera para tirar a foto.'); return } } const result = await (camera ? ImagePicker.launchCameraAsync : ImagePicker.launchImageLibraryAsync)({ mediaTypes: ['images'], base64: true, quality: 0.8, exif: false }); if (result.canceled) return; const asset = result.assets[0]; if (!asset?.base64 || !asset.mimeType || !['image/jpeg', 'image/png', 'image/webp'].includes(asset.mimeType)) { setError('Selecione uma imagem JPEG, PNG ou WebP.'); return } if ((asset.fileSize ?? Math.floor(asset.base64.length * 3 / 4)) > 5 * 1024 * 1024) { setError('A imagem deve ter no máximo 5 MiB.'); return } setImage({ base64: asset.base64, mimeType: asset.mimeType as 'image/jpeg' | 'image/png' | 'image/webp' }) }
  const run = async () => { setError(''); setBusy(true); try { const profile = await repositories.userProfile.get(); const result = action === 'text' ? await client.parseMeal({ text, context: buildMealParseContext(profile) }) : await client.analyzeMealImage({ image: { ...image!, userHint: hint || undefined }, context: buildMealVisionContext(profile, hint) }); onReview(await toMealDraft(date, result.items, action === 'image')); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível interpretar a refeição.') } finally { setBusy(false) } }
  if (!enabled) return <View style={{ gap: 12 }}><SectionHeader title="IA opcional" /><InlineNotice tone="warning" message={AI_PRIVACY_NOTICE} /><Button color={colors.primary} label="Continuar e habilitar IA" onPress={() => void accept()} /></View>
  if (!available) return <InlineNotice tone="warning" message="IA indisponível neste momento. O registro manual continua disponível." />
  return <View style={{ gap: 12 }}><SectionHeader title={action === 'text' ? 'Adicionar com IA' : 'Analisar foto com IA'} />{!!error && <InlineNotice tone="danger" message={error} />}{action === 'text' ? <Input color={colors.textPrimary} border={colors.border} placeholder={colors.textSecondary} label="Descreva a refeição" value={text} onChangeText={setText} placeholderText="Ex.: 200g arroz, 150g frango e dois ovos" /> : <><View style={{ flexDirection: 'row', gap: 8 }}><Button color={colors.primary} label={image ? 'Trocar imagem' : 'Galeria'} onPress={() => void chooseImage()} /><Button color={colors.primary} label="Câmera" onPress={() => void chooseImage(true)} /></View><Input color={colors.textPrimary} border={colors.border} placeholder={colors.textSecondary} label="Detalhes da foto" value={hint} onChangeText={setHint} placeholderText="Opcional: o frango tem 200g" /></>}<Button color={colors.primary} disabled={busy || (action === 'text' ? !text.trim() : !image)} label={busy ? 'Interpretando…' : 'Gerar revisão'} onPress={() => void run()} /></View>
}

function Input({ color, border, placeholder, label, value, onChangeText, placeholderText }: { color: string; border: string; placeholder: string; label: string; value: string; onChangeText: (value: string) => void; placeholderText: string }) { return <TextInput accessibilityLabel={label} multiline onChangeText={onChangeText} placeholder={placeholderText} placeholderTextColor={placeholder} style={{ borderColor: border, borderRadius: 10, borderWidth: 1, color, minHeight: 72, padding: 12 }} value={value} /> }
function Button({ color, label, onPress, disabled }: { color: string; label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={{ backgroundColor: color, borderRadius: 10, flex: 1, justifyContent: 'center', minHeight: 48, opacity: disabled ? 0.55 : 1, paddingHorizontal: 16 }}><Text style={{ color: '#fff', fontWeight: '800', textAlign: 'center' }}>{label}</Text></Pressable> }

async function toMealDraft(date: string, items: readonly FoodQueryDraft[], estimated: boolean): Promise<NutritionMealDraft> {
  const resolver = new FoodResolver([new LocalFoodCatalogProvider(LOCAL_FOOD_CATALOG)]); const draft = createEmptyNutritionMealDraft(date)
  draft.items = await Promise.all(items.map(async (item) => { const resolved = await resolver.resolve({ text: item.query }); const food = resolved.status === 'exact' || resolved.status === 'probable' ? resolved.candidates[0] : null; const quantity = item.quantity; const unit = item.unit
    if (food && quantity && unit === food.servingBasis.unit) { const nutrients = NutritionCalculator.calculatePortion(food, { amount: quantity, unit }).nutrients; return { name: food.name, portionDescription: `${estimated ? '~' : ''}${quantity} ${unit}`, estimatedGrams: unit === 'g' ? String(quantity) : '', caloriesKcal: String(nutrients.energyKcal), proteinGrams: String(nutrients.proteinG), carbohydratesGrams: String(nutrients.carbsG), fatGrams: String(nutrients.fatG), fiberGrams: String(nutrients.fiberG), micronutrients: {} } }
    return { name: item.query, portionDescription: quantity ? `${estimated ? '~' : ''}${quantity} ${unit ?? ''}`.trim() : 'Quantidade a confirmar', estimatedGrams: unit === 'g' && quantity ? String(quantity) : '', caloriesKcal: '', proteinGrams: '', carbohydratesGrams: '', fatGrams: '', fiberGrams: '', micronutrients: {} }
  }))
  return draft
}
