import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native'
import { localDateKey, type NutritionMeal, type NutritionMealInput, type NutritionMealItemInput, type NutritionGoals } from '@training/training-domain'
import type { LocalRepositories } from '@training/training-local-db'
import { EmptyState, InlineNotice, MetricCard, SectionHeader, StatusPill } from '../../components/ui'
import { ScreenScrollView } from '../../components/Screen'
import { ScreenHeader } from '../../components/ScreenHeader'
import { useTheme, type ThemeColors } from '../../theme'
import { typography } from '../../theme/typography'

const emptyGoals: NutritionGoals = { caloriesKcal: null, proteinGrams: null, carbohydratesGrams: null, fatGrams: null, fiberGrams: null }
const emptyItem = (): NutritionMealItemInput => ({ name: '', portionDescription: '', estimatedGrams: null, caloriesKcal: 0, proteinGrams: 0, carbohydratesGrams: 0, fatGrams: 0, fiberGrams: 0, micronutrients: {}, confidence: null, dataSource: 'MANUAL', sortOrder: 0 })
const goalKey = 'nutrition.goals'

export function NutritionScreen({ repositories }: { repositories: LocalRepositories }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const today = localDateKey(new Date())
  const [date, setDate] = useState(today); const [meals, setMeals] = useState<NutritionMeal[]>([]); const [summary, setSummary] = useState<any>(null); const [goals, setGoals] = useState(emptyGoals); const [editing, setEditing] = useState<NutritionMeal | null>(null); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false)
  const refresh = useCallback(async () => { setLoading(true); try { const [nextMeals, nextSummary, stored] = await Promise.all([repositories.nutritionMeals.listByDate(date), repositories.nutritionSummaries.findByDate(date), repositories.settings.get<unknown>(goalKey)]); setMeals(nextMeals); setSummary(nextSummary); if (stored && typeof stored === 'object') setGoals({ ...emptyGoals, ...(stored as NutritionGoals) }) } finally { setLoading(false) } }, [date, repositories])
  useEffect(() => { void refresh() }, [refresh])
  const save = async (input: NutritionMealInput) => { try { await (editing ? repositories.nutritionMeals.update(editing.id, input) : repositories.nutritionMeals.create(input)); await repositories.nutritionMaintenance.aggregateDay(input.localDate); setEditing(null); await refresh() } catch (error) { setNotice(error instanceof Error ? error.message : 'Não foi possível salvar a refeição.') } }
  const remove = (meal: NutritionMeal) => Alert.alert('Excluir refeição?', meal.title || mealType(meal.mealType), [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { await repositories.nutritionMeals.delete(meal.id); await repositories.nutritionMaintenance.aggregateDay(meal.localDate); await refresh() } }])
  const changeDate = (delta: number) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + delta); setDate(localDateKey(next)) }
  if (editing) return <MealForm initial={editing} onCancel={() => setEditing(null)} onSave={save} />
  return <ScreenScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void refresh()} tintColor={colors.primary} />}>
    <ScreenHeader eyebrow="Local e privado" title="Nutrição" description={readableDate(date)} />
    <View style={styles.dateRow}><Pressable accessibilityLabel="Dia anterior" onPress={() => changeDate(-1)}><Text style={styles.arrow}>‹</Text></Pressable><Text style={styles.date}>{date === today ? 'Hoje' : date}</Text><Pressable accessibilityLabel="Próximo dia" onPress={() => changeDate(1)}><Text style={styles.arrow}>›</Text></Pressable></View>
    {!!notice && <InlineNotice tone="warning" message={notice} />}
    <SectionHeader title="Resumo diário" />
    <View style={styles.metrics}><MetricCard label="Calorias" value={`${summary?.totalCaloriesKcal ?? sum(meals, 'caloriesKcal')} kcal`} /><MetricCard label="Proteína" value={`${summary?.totalProteinGrams ?? sum(meals, 'proteinGrams')} g`} /><MetricCard label="Carboidratos" value={`${summary?.totalCarbohydratesGrams ?? sum(meals, 'carbohydratesGrams')} g`} /><MetricCard label="Gordura" value={`${summary?.totalFatGrams ?? sum(meals, 'fatGrams')} g`} /></View>
    <Text style={styles.helper}>{summary?.goalCaloriesKcal ? `Meta configurada: ${summary.goalCaloriesKcal} kcal` : 'Configure suas metas nesta tela quando quiser.'} · {meals.length} refeição(ões)</Text>
    <SectionHeader title="Adicionar" />
    <View style={styles.actions}><Action label="Câmera" onPress={() => setNotice('A análise por imagem será adicionada na próxima etapa.')} /><Action label="Galeria" onPress={() => setNotice('A análise por imagem será adicionada na próxima etapa.')} /><Action label="Adicionar manualmente" primary onPress={() => setEditing({ id: 0, localDate: date, consumedAt: new Date().toISOString(), mealType: 'OTHER', title: '', notes: '', source: 'MANUAL', createdAt: '', updatedAt: '', items: [emptyItem() as never] })} /></View>
    <SectionHeader title="Refeições" />
    {!meals.length ? <EmptyState title="Nenhuma refeição registrada hoje." description="Adicione manualmente para começar seu resumo diário." /> : meals.map((meal) => <View key={meal.id} style={styles.meal}><View style={styles.mealHeader}><StatusPill label={mealType(meal.mealType)} /><Text style={styles.time}>{new Date(meal.consumedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></View><Text style={styles.mealTitle}>{meal.title || 'Refeição sem título'}</Text><Text style={styles.detail}>{meal.items.length} item(ns) · {sumItems(meal, 'caloriesKcal')} kcal · {sumItems(meal, 'proteinGrams')} g proteína</Text><View style={styles.row}><Action label="Abrir / editar" onPress={() => setEditing(meal)} /><Action label="Excluir" onPress={() => remove(meal)} /></View></View>)}
    <SectionHeader title="Metas nutricionais" /><Text style={styles.helper}>Estas metas são definidas por você e não substituem orientação profissional.</Text><GoalFields goals={goals} onSave={async (next) => { await repositories.settings.set(goalKey, next); setGoals(next); setNotice('Metas salvas.') }} />
  </ScreenScrollView>
}

function MealForm({ initial, onCancel, onSave }: { initial: NutritionMeal; onCancel: () => void; onSave: (input: NutritionMealInput) => Promise<void> }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const [meal, setMeal] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const updateItem = (index: number, field: keyof NutritionMealItemInput, value: string) => setMeal((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: ['caloriesKcal', 'proteinGrams', 'carbohydratesGrams', 'fatGrams'].includes(field) ? Number(value.replace(',', '.')) : value } : item) }))
  const submit = async () => { setError(''); if (!meal.items.length || meal.items.some((item) => !item.name.trim() || Object.values(item).some((value) => typeof value === 'number' && !Number.isFinite(value)))) { setError('Informe o nome e valores válidos para pelo menos um alimento.'); return } setBusy(true); try { await onSave({ localDate: meal.localDate, consumedAt: meal.consumedAt, mealType: meal.mealType, title: meal.title, notes: meal.notes, source: 'MANUAL', items: meal.items.map((item, index) => ({ ...item, sortOrder: index })) }) } catch {} finally { setBusy(false) } }
  return <ScreenScrollView><ScreenHeader eyebrow="Nutrição" title={initial.id ? 'Editar refeição' : 'Adicionar refeição'} description="Os valores são informados manualmente." />{!!error && <InlineNotice tone="danger" message={error} />}<Text style={styles.label}>Tipo</Text><View style={styles.actions}>{(['BREAKFAST', 'MORNING_SNACK', 'LUNCH', 'AFTERNOON_SNACK', 'DINNER', 'SUPPER', 'OTHER'] as const).map((type) => <Action key={type} label={mealType(type)} primary={meal.mealType === type} onPress={() => setMeal({ ...meal, mealType: type })} />)}</View><Field label="Título (opcional)" value={meal.title} onChangeText={(title) => setMeal({ ...meal, title })} /><SectionHeader title="Alimentos" />{meal.items.map((item, index) => <View key={index} style={styles.itemForm}><Field label="Nome" value={item.name} onChangeText={(value) => updateItem(index, 'name', value)} /><Field label="Porção" value={item.portionDescription} onChangeText={(value) => updateItem(index, 'portionDescription', value)} /><View style={styles.two}><View style={styles.twoChild}><Field label="Calorias" keyboardType="decimal-pad" value={String(item.caloriesKcal)} onChangeText={(value) => updateItem(index, 'caloriesKcal', value)} /></View><View style={styles.twoChild}><Field label="Proteína (g)" keyboardType="decimal-pad" value={String(item.proteinGrams)} onChangeText={(value) => updateItem(index, 'proteinGrams', value)} /></View></View><View style={styles.two}><View style={styles.twoChild}><Field label="Carboidratos (g)" keyboardType="decimal-pad" value={String(item.carbohydratesGrams)} onChangeText={(value) => updateItem(index, 'carbohydratesGrams', value)} /></View><View style={styles.twoChild}><Field label="Gordura (g)" keyboardType="decimal-pad" value={String(item.fatGrams)} onChangeText={(value) => updateItem(index, 'fatGrams', value)} /></View></View><Action label="Remover alimento" onPress={() => setMeal({ ...meal, items: meal.items.filter((_, itemIndex) => itemIndex !== index) })} /></View>)}<Action label="Adicionar alimento" onPress={() => setMeal({ ...meal, items: [...meal.items, emptyItem() as never] })} /><View style={styles.row}><Action label="Cancelar" onPress={onCancel} /><Action label={busy ? 'Salvando…' : 'Salvar refeição'} primary onPress={() => void submit()} /></View></ScreenScrollView>
}
function GoalFields({ goals, onSave }: { goals: NutritionGoals; onSave: (value: NutritionGoals) => Promise<void> }) { const [values, setValues] = useState(goals); return <View>{(['caloriesKcal', 'proteinGrams', 'carbohydratesGrams', 'fatGrams', 'fiberGrams'] as const).map((key) => <Field key={key} label={key === 'caloriesKcal' ? 'Calorias (kcal)' : `${key.replace('Grams', '')} (g)`} keyboardType="decimal-pad" value={values[key] == null ? '' : String(values[key])} onChangeText={(value) => setValues({ ...values, [key]: value ? Number(value.replace(',', '.')) : null })} />)}<Action label="Salvar metas" primary onPress={() => void onSave(values)} /></View> }
function Field(props: React.ComponentProps<typeof TextInput> & { label: string }) { const { colors } = useTheme(); return <View style={{ marginBottom: 10 }}><Text style={{ ...typography.caption, color: colors.textSecondary, marginBottom: 4 }}>{props.label}</Text><TextInput {...props} style={{ borderColor: colors.border, borderRadius: 12, borderWidth: 1, color: colors.textPrimary, minHeight: 46, paddingHorizontal: 12 }} placeholderTextColor={colors.textSecondary} /> </View> }
function Action({ label, onPress, primary }: { label: string; onPress: () => void; primary?: boolean }) { const { colors } = useTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={{ backgroundColor: primary ? colors.primary : colors.surface, borderColor: primary ? colors.primary : colors.border, borderRadius: 12, borderWidth: 1, minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 }}><Text style={{ color: primary ? colors.onPrimary : colors.textPrimary, fontWeight: '800' }}>{label}</Text></Pressable> }
const mealType = (type: NutritionMeal['mealType']) => ({ BREAKFAST: 'Café da manhã', MORNING_SNACK: 'Lanche da manhã', LUNCH: 'Almoço', AFTERNOON_SNACK: 'Lanche da tarde', DINNER: 'Jantar', SUPPER: 'Ceia', OTHER: 'Outro' })[type]
const sum = (meals: NutritionMeal[], key: 'caloriesKcal' | 'proteinGrams' | 'carbohydratesGrams' | 'fatGrams') => meals.reduce((total, meal) => total + sumItems(meal, key), 0)
const sumItems = (meal: NutritionMeal, key: 'caloriesKcal' | 'proteinGrams' | 'carbohydratesGrams' | 'fatGrams') => meal.items.reduce((total, item) => total + item[key], 0)
const readableDate = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' })
const createStyles = (colors: ThemeColors) => StyleSheet.create({ dateRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 }, arrow: { color: colors.primary, fontSize: 36, paddingHorizontal: 16 }, date: { ...typography.body, color: colors.textPrimary, fontWeight: '800' }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, helper: { ...typography.bodySmall, color: colors.textSecondary, marginVertical: 10 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 }, meal: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, marginBottom: 10, padding: 14 }, mealHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, time: { color: colors.textSecondary }, mealTitle: { ...typography.body, color: colors.textPrimary, fontWeight: '800', marginTop: 10 }, detail: { ...typography.bodySmall, color: colors.textSecondary, marginVertical: 6 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 }, label: { ...typography.caption, color: colors.textSecondary, marginBottom: 6 }, itemForm: { borderColor: colors.border, borderRadius: 16, borderWidth: 1, marginBottom: 12, padding: 12 }, two: { flexDirection: 'row', gap: 8 }, twoChild: { flex: 1 } })
