import { useMemo, useRef, useState } from 'react'
import { Ionicons } from '@expo/vector-icons'
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { EXERCISE_PACKS, type ExerciseDefinition } from '@training/training-domain'
import { BottomSheet } from '../../../components/ui/BottomSheet'
import { SelectableChip } from '../../../components/SelectableChip'
import { ThemedTextInput } from '../../../components/ThemedTextInput'
import { shared, type ThemeColors, useTheme } from '../../../theme'
import { filterExerciseLibrary, libraryEmptyMessage, type LibraryFilter } from '../../exercise-library/libraryState'

export function ExercisePicker({ exercises, excludedId, onFavorite, onSelect }: { exercises: ExerciseDefinition[]; excludedId?: number; onFavorite?: (id: number, favorite: boolean) => Promise<boolean>; onSelect: (exercise: ExerciseDefinition) => void }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<LibraryFilter>({ kind: 'ALL' }); const [filtersOpen, setFiltersOpen] = useState(false); const lastSelection = useRef({ id: 0, at: 0 })
  const available = useMemo(() => exercises.filter((exercise) => !exercise.archived && exercise.id !== excludedId), [excludedId, exercises]); const muscles = useMemo(() => [...new Set(available.map((exercise) => exercise.primaryMuscleGroup))].sort(), [available]); const equipment = useMemo(() => [...new Set(available.map((exercise) => exercise.equipment))].sort(), [available]); const filtered = useMemo(() => filterExerciseLibrary(available, query, filter), [available, filter, query]); const filterLabel = filter.kind === 'ALL' ? 'Filtros' : 'Filtros 1'
  const select = (exercise: ExerciseDefinition) => { const now = Date.now(); if (lastSelection.current.id === exercise.id && now - lastSelection.current.at < 800) return; lastSelection.current = { id: exercise.id, at: now }; onSelect(exercise) }
  const clear = () => setFilter({ kind: 'ALL' })
  return <>
    <FlatList data={filtered} keyExtractor={(item) => String(item.id)} keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.content, !filtered.length && styles.emptyContent]} ListHeaderComponent={<View><ThemedTextInput accessibilityLabel="Buscar exercício" placeholder="Nome, alias, músculo ou equipamento" style={styles.search} value={query} onChangeText={setQuery} /><View style={styles.quickFilters}><QuickFilter label="Favoritos" value={{ kind: 'FAVORITES' }} selected={filter} onSelect={setFilter} /><QuickFilter label="Recentes" value={{ kind: 'RECENTS' }} selected={filter} onSelect={setFilter} /><TouchableOpacity accessibilityRole="button" accessibilityLabel={filterLabel} accessibilityState={{ expanded: filtersOpen }} onPress={() => setFiltersOpen(true)} style={[styles.filterAction, filter.kind !== 'ALL' && styles.filterActive]}><Text style={styles.filterText}>{filterLabel}</Text></TouchableOpacity></View>{filter.kind !== 'ALL' && <TouchableOpacity accessibilityRole="button" accessibilityLabel="Limpar filtro" onPress={clear} style={styles.clearFilter}><Text style={styles.clearFilterText}>Limpar filtro</Text></TouchableOpacity>}</View>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>{libraryEmptyMessage(available.length, query, filter)}</Text>{filter.kind !== 'ALL' && <TouchableOpacity accessibilityRole="button" accessibilityLabel="Limpar filtro" onPress={clear} style={styles.emptyAction}><Text style={styles.clearFilterText}>Limpar filtro</Text></TouchableOpacity>}</View>} renderItem={({ item, index }) => <View style={[styles.item, index > 0 && styles.divider]}><TouchableOpacity accessibilityLabel={`Selecionar ${item.name}, ${item.primaryMuscleGroup}, ${item.equipment}`} accessibilityRole="button" onPress={() => select(item)} style={styles.itemMain}><View style={styles.itemCopy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.primaryMuscleGroup} · {item.equipment}</Text></View><Ionicons accessibilityElementsHidden color={colors.textSecondary} name="chevron-forward" size={20} /></TouchableOpacity>{!!onFavorite && <Pressable accessibilityLabel={item.favorite ? `Remover ${item.name} dos favoritos` : `Favoritar ${item.name}`} accessibilityRole="button" accessibilityState={{ selected: item.favorite }} onPress={() => void onFavorite(item.id, !item.favorite)} style={styles.favorite}><Ionicons color={colors.primary} name={item.favorite ? 'star' : 'star-outline'} size={22} /></Pressable>}</View>} />
    <BottomSheet visible={filtersOpen} title="Filtros" description="Escolha um filtro para a biblioteca." onClose={() => setFiltersOpen(false)}><ScrollView contentContainerStyle={styles.sheetContent} showsVerticalScrollIndicator><FilterGroup label="PACOTE">{EXERCISE_PACKS.map((pack) => <SheetFilter key={pack.id} label={pack.name} value={{ kind: 'PACK', value: pack.id }} selected={filter} onSelect={(next) => { setFilter(next); setFiltersOpen(false) }} />)}</FilterGroup><FilterGroup label="GRUPO MUSCULAR">{muscles.map((muscle) => <SheetFilter key={muscle} label={muscle} value={{ kind: 'MUSCLE', value: muscle }} selected={filter} onSelect={(next) => { setFilter(next); setFiltersOpen(false) }} />)}</FilterGroup><FilterGroup label="EQUIPAMENTO">{equipment.map((item) => <SheetFilter key={item} label={item} value={{ kind: 'EQUIPMENT', value: item }} selected={filter} onSelect={(next) => { setFilter(next); setFiltersOpen(false) }} />)}</FilterGroup><SheetFilter label="Peso corporal" value={{ kind: 'BODYWEIGHT' }} selected={filter} onSelect={(next) => { setFilter(next); setFiltersOpen(false) }} /></ScrollView></BottomSheet>
  </>
}
function QuickFilter({ label, value, selected, onSelect }: { label: string; value: LibraryFilter; selected: LibraryFilter; onSelect: (value: LibraryFilter) => void }) { const active = sameFilter(value, selected); return <SelectableChip label={label} selected={active} onPress={() => onSelect(active ? { kind: 'ALL' } : value)} /> }
function SheetFilter({ label, value, selected, onSelect }: { label: string; value: LibraryFilter; selected: LibraryFilter; onSelect: (value: LibraryFilter) => void }) { const { colors } = useTheme(); const styles = createStyles(colors); const active = sameFilter(value, selected); return <Pressable accessibilityRole="radio" accessibilityLabel={label} accessibilityState={{ checked: active }} onPress={() => onSelect(active ? { kind: 'ALL' } : value)} style={styles.sheetFilter}><Text style={styles.sheetFilterText}>{label}</Text>{active && <Text style={styles.selected}>Selecionado</Text>}</Pressable> }
function FilterGroup({ label, children }: { label: string; children: React.ReactNode }) { const { colors } = useTheme(); const styles = createStyles(colors); return <View><Text style={styles.groupLabel}>{label}</Text>{children}</View> }
function sameFilter(first: LibraryFilter, second: LibraryFilter) { return first.kind === second.kind && (!('value' in first) || ('value' in second && first.value === second.value)) }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ content: { paddingBottom: 45, paddingHorizontal: shared.pagePadding }, emptyContent: { flexGrow: 1 }, search: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 15, borderWidth: 1, color: colors.textPrimary, fontSize: 16, marginBottom: 10, minHeight: 56, paddingHorizontal: 16 }, quickFilters: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 6 }, filterAction: { alignItems: 'center', borderColor: colors.border, borderRadius: 999, borderWidth: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 14 }, filterActive: { borderColor: colors.primary }, filterText: { color: colors.textPrimary, fontSize: 14, fontWeight: '600' }, clearFilter: { alignSelf: 'flex-start', justifyContent: 'center', minHeight: 48, marginBottom: 6 }, clearFilterText: { color: colors.primary, fontSize: 13, fontWeight: '700' }, item: { alignItems: 'center', flexDirection: 'row', minHeight: 64 }, divider: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth }, itemMain: { alignItems: 'center', flex: 1, flexDirection: 'row', minHeight: 64, minWidth: 0, paddingVertical: 9 }, itemCopy: { flex: 1, minWidth: 0, paddingRight: 12 }, name: { color: colors.textPrimary, fontSize: 16, fontWeight: '600', lineHeight: 22 }, meta: { color: colors.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 2 }, favorite: { alignItems: 'center', justifyContent: 'center', minHeight: 48, minWidth: 48 }, empty: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 230 }, emptyTitle: { color: colors.textPrimary, fontSize: 14, fontWeight: '600', textAlign: 'center' }, emptyAction: { justifyContent: 'center', minHeight: 48, marginTop: 6 }, sheetContent: { gap: 14, paddingBottom: 12 }, groupLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', letterSpacing: .8, marginBottom: 4 }, sheetFilter: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 48 }, sheetFilterText: { color: colors.textPrimary, flex: 1, fontSize: 15 }, selected: { color: colors.primary, fontSize: 12, fontWeight: '700' } })
