import { StyleSheet, Text, View } from 'react-native'
import { WEEKDAYS, analyzeTrainingPlanWeekPreview, type TrainingPlanDayCreationInput, type Weekday } from '@training/training-domain'
import { shared, type ThemeColors, useTheme } from '../../../theme'

type PreviewDay = TrainingPlanDayCreationInput & { exercises?: readonly unknown[]; restActivities?: readonly unknown[] }
const abbreviations: Record<Weekday, string> = { MONDAY: 'SEG', TUESDAY: 'TER', WEDNESDAY: 'QUA', THURSDAY: 'QUI', FRIDAY: 'SEX', SATURDAY: 'SÁB', SUNDAY: 'DOM' }

export function TrainingPlanWeekPreview({ days }: { days: readonly PreviewDay[] }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const ordered = WEEKDAYS.map((weekday) => days.find((day) => day.weekday === weekday)); const warnings = analyzeTrainingPlanWeekPreview(days)
  return <View accessibilityLabel="Prévia da estrutura semanal" style={styles.group}>{ordered.map((day, index) => { const exerciseCount = day?.exercises?.length ?? 0; const activityCount = day?.restActivities?.length ?? 0; const warning = day && !day.restDay && exerciseCount === 0; return <View key={WEEKDAYS[index]} accessibilityLabel={day ? `${abbreviations[day.weekday]}, ${day.title}, ${day.restDay ? 'descanso' : 'treino'}, ${exerciseCount} exercícios, ${activityCount} atividades` : `${abbreviations[WEEKDAYS[index]!]}, dia ausente`} style={[styles.row, index > 0 && styles.divider, day?.restDay && styles.restRow]}><Text style={[styles.weekday, warning && styles.warningText]}>{abbreviations[WEEKDAYS[index]!]}</Text><Text numberOfLines={1} style={styles.title}>{day?.title || 'Dia vazio'}</Text><Text style={[styles.meta, warning && styles.warningText]}>{day?.restDay ? 'Descanso' : warning ? 'Sem exercícios' : 'Treino'}</Text></View> })}{warnings.map((warning, index) => <Text key={`${warning.code}:${'weekday' in warning ? warning.weekday : index}`} style={styles.notice}>{warning.message}</Text>)}</View>
}

const createStyles = (colors: ThemeColors) => StyleSheet.create({ group: { backgroundColor: colors.surfaceSecondary, borderRadius: 16, overflow: 'hidden' }, row: { alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 44, paddingHorizontal: 12 }, divider: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth }, restRow: { backgroundColor: colors.surface }, weekday: { color: colors.primary, fontSize: 12, fontWeight: '700', width: 32 }, title: { color: colors.textPrimary, flex: 1, fontSize: 14, fontWeight: '600' }, meta: { color: colors.textSecondary, fontSize: 12 }, warningText: { color: colors.warning }, notice: { color: colors.warning, fontSize: 13, lineHeight: 18, paddingHorizontal: shared.spacing.sm, paddingTop: shared.spacing.sm } })
