CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL, description VARCHAR(500), scheduled_date DATE NOT NULL,
    status VARCHAR(24) NOT NULL, duration_minutes INTEGER NOT NULL, calories INTEGER NOT NULL,
    custom_stats TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL REFERENCES workouts(id), name VARCHAR(120) NOT NULL,
    muscle_group VARCHAR(80) NOT NULL, sets INTEGER NOT NULL, reps INTEGER NOT NULL,
    weight_kg NUMERIC(8,2) NOT NULL, rest_seconds INTEGER NOT NULL, custom_stats TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE training_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL, description VARCHAR(500), category VARCHAR(80) NOT NULL,
    difficulty VARCHAR(40) NOT NULL, active BOOLEAN NOT NULL, archived BOOLEAN NOT NULL,
    start_date DATE, end_date DATE, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE plan_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_plan_id BIGINT NOT NULL REFERENCES training_plans(id), name VARCHAR(120) NOT NULL,
    muscle_group VARCHAR(80) NOT NULL, sets INTEGER NOT NULL, reps INTEGER NOT NULL,
    weight_kg NUMERIC(8,2) NOT NULL, rest_seconds INTEGER NOT NULL, custom_stats TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE exercise_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_name VARCHAR(140) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL,
    description VARCHAR(600), primary_muscle_group VARCHAR(80) NOT NULL,
    secondary_muscle_groups VARCHAR(300), equipment VARCHAR(80) NOT NULL,
    category VARCHAR(30) NOT NULL, difficulty VARCHAR(40) NOT NULL, instructions VARCHAR(1500),
    notes VARCHAR(600), media_url VARCHAR(500), source VARCHAR(20) NOT NULL,
    external_id VARCHAR(100), external_base_id VARCHAR(100), source_url VARCHAR(1000),
    license_name VARCHAR(200), license_url VARCHAR(1000), author VARCHAR(500),
    last_synced_at TIMESTAMPTZ, upstream_updated_at TIMESTAMPTZ,
    unilateral BOOLEAN NOT NULL, timed BOOLEAN NOT NULL, custom BOOLEAN NOT NULL,
    archived BOOLEAN NOT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_exercise_definition_source_external UNIQUE(source, external_id)
);
CREATE TABLE exercise_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_definition_id BIGINT NOT NULL REFERENCES exercise_definitions(id),
    type VARCHAR(20) NOT NULL, source VARCHAR(20) NOT NULL, external_id VARCHAR(100),
    url VARCHAR(1000) NOT NULL, thumbnail_url VARCHAR(1000), mime_type VARCHAR(100),
    width INTEGER, height INTEGER, duration_seconds INTEGER, is_main BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL, license_name VARCHAR(200), license_url VARCHAR(1000),
    author VARCHAR(500), source_url VARCHAR(1000), created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_exercise_media_source_external UNIQUE(source, external_id)
);
CREATE TABLE training_plan_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_plan_id BIGINT NOT NULL REFERENCES training_plans(id), weekday VARCHAR(12) NOT NULL,
    title VARCHAR(120), description VARCHAR(500), sort_order INTEGER NOT NULL,
    rest_day BOOLEAN NOT NULL, estimated_duration_minutes INTEGER NOT NULL, notes VARCHAR(600),
    CONSTRAINT uq_training_plan_weekday UNIQUE(training_plan_id, weekday)
);
CREATE TABLE training_day_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id BIGINT NOT NULL REFERENCES training_plan_days(id),
    exercise_definition_id BIGINT NOT NULL REFERENCES exercise_definitions(id),
    sort_order INTEGER NOT NULL, sets INTEGER NOT NULL, min_reps INTEGER NOT NULL,
    max_reps INTEGER NOT NULL, planned_load NUMERIC(8,2), planned_duration_seconds INTEGER,
    planned_distance NUMERIC(10,2), rest_seconds INTEGER NOT NULL, planned_rpe NUMERIC(3,1),
    set_type VARCHAR(30) NOT NULL, notes VARCHAR(600),
    alternative_exercise_id BIGINT REFERENCES exercise_definitions(id)
);
CREATE TABLE rest_day_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id BIGINT NOT NULL REFERENCES training_plan_days(id), name VARCHAR(120) NOT NULL,
    description VARCHAR(500), estimated_duration_minutes INTEGER NOT NULL,
    category VARCHAR(80) NOT NULL, optional BOOLEAN NOT NULL, sort_order INTEGER NOT NULL
);
CREATE TABLE workout_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_plan_id BIGINT REFERENCES training_plans(id), plan_day_id BIGINT REFERENCES training_plan_days(id),
    workout_name_snapshot VARCHAR(120) NOT NULL, scheduled_date DATE NOT NULL,
    started_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ, paused_at TIMESTAMPTZ,
    status VARCHAR(24) NOT NULL, paused_duration_seconds BIGINT NOT NULL,
    total_duration_seconds INTEGER NOT NULL, overall_rpe NUMERIC(3,1), notes VARCHAR(1000)
);
CREATE TABLE workout_session_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES workout_sessions(id), exercise_definition_id BIGINT,
    exercise_name_snapshot VARCHAR(120) NOT NULL, muscle_group_snapshot VARCHAR(80) NOT NULL,
    category_snapshot VARCHAR(30), timed_snapshot BOOLEAN, primary_video_url VARCHAR(1000),
    primary_image_url VARCHAR(1000), attribution VARCHAR(1000), sort_order INTEGER NOT NULL,
    planned_sets INTEGER NOT NULL, planned_min_reps INTEGER NOT NULL, planned_max_reps INTEGER NOT NULL,
    rest_seconds INTEGER NOT NULL, status VARCHAR(24) NOT NULL, notes VARCHAR(600)
);
CREATE TABLE workout_set_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_exercise_id BIGINT NOT NULL REFERENCES workout_session_exercises(id),
    set_number INTEGER NOT NULL, reps INTEGER NOT NULL, load NUMERIC(8,2) NOT NULL,
    duration_seconds INTEGER NOT NULL, distance NUMERIC(10,2) NOT NULL, rpe NUMERIC(3,1),
    completed BOOLEAN NOT NULL, completed_at TIMESTAMPTZ, manually_added BOOLEAN, notes VARCHAR(500)
);
CREATE TABLE workout_session_lock (id INTEGER PRIMARY KEY);
INSERT INTO workout_session_lock(id) VALUES (1);
CREATE TABLE wger_sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(20) NOT NULL, dry_run BOOLEAN NOT NULL, started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ, pages INTEGER NOT NULL, created INTEGER NOT NULL,
    updated INTEGER NOT NULL, skipped INTEGER NOT NULL, failed INTEGER NOT NULL, message VARCHAR(500)
);
CREATE TABLE uma_careers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL, training_plan_id BIGINT NOT NULL REFERENCES training_plans(id),
    status VARCHAR(16) NOT NULL, active_slot INTEGER UNIQUE, total_weeks INTEGER NOT NULL,
    current_week INTEGER NOT NULL, current_weekday VARCHAR(12) NOT NULL,
    strength INTEGER NOT NULL, endurance INTEGER NOT NULL, agility INTEGER NOT NULL,
    technique INTEGER NOT NULL, discipline INTEGER NOT NULL, energy INTEGER NOT NULL,
    fatigue INTEGER NOT NULL, mood INTEGER NOT NULL, confidence INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ, version BIGINT NOT NULL
);
CREATE TABLE uma_career_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_id BIGINT NOT NULL REFERENCES uma_careers(id), week_number INTEGER NOT NULL,
    weekday VARCHAR(12) NOT NULL, action_type VARCHAR(20) NOT NULL, status VARCHAR(16) NOT NULL,
    training_plan_day_id BIGINT REFERENCES training_plan_days(id), workout_session_id BIGINT UNIQUE,
    rest_activity_id BIGINT, action_title_snapshot VARCHAR(120) NOT NULL,
    activity_category_snapshot VARCHAR(80), activity_duration_minutes_snapshot INTEGER,
    result_text VARCHAR(1000) NOT NULL, strength_delta INTEGER NOT NULL,
    endurance_delta INTEGER NOT NULL, agility_delta INTEGER NOT NULL, technique_delta INTEGER NOT NULL,
    discipline_delta INTEGER NOT NULL, energy_delta INTEGER NOT NULL, fatigue_delta INTEGER NOT NULL,
    mood_delta INTEGER NOT NULL, confidence_delta INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ,
    CONSTRAINT uq_uma_career_turn UNIQUE(career_id, week_number, weekday)
);
CREATE INDEX idx_exercise_definition_filters ON exercise_definitions(archived, source, category, name);
CREATE INDEX idx_exercise_media_exercise ON exercise_media(exercise_definition_id, type, sort_order);
CREATE INDEX idx_session_status ON workout_sessions(status, started_at);
