package com.trainingapp.config;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TrainingPlanWeekMigrationTest {

    @Test
    void consolidatesEmptyDuplicatesCompletesWeekAndIsIdempotent() throws Exception {
        DataSource dataSource = legacyDatabase("repair");
        execute(dataSource, """
                INSERT INTO training_plans (id) VALUES (1);
                INSERT INTO training_plan_days
                    (training_plan_id, weekday, title, description, sort_order, rest_day,
                     estimated_duration_minutes, notes)
                VALUES
                    (1, 'MONDAY', '', '', 1, FALSE, 0, ''),
                    (1, 'MONDAY', '', '', 1, FALSE, 0, '');
                """);

        TrainingPlanWeekMigration migration = new TrainingPlanWeekMigration(dataSource);
        migration.migrate();
        migration.migrate();

        assertEquals(7, count(dataSource, "SELECT COUNT(*) FROM training_plan_days"));
        Set<String> weekdays = new HashSet<>();
        try (Connection connection = dataSource.getConnection();
             var rows = connection.createStatement().executeQuery(
                     "SELECT weekday FROM training_plan_days WHERE training_plan_id = 1")) {
            while (rows.next()) weekdays.add(rows.getString(1));
        }
        assertEquals(7, weekdays.size());
        assertThrows(SQLException.class, () -> execute(dataSource, """
                INSERT INTO training_plan_days
                    (training_plan_id, weekday, title, description, sort_order, rest_day,
                     estimated_duration_minutes, notes)
                VALUES (1, 'MONDAY', '', '', 1, FALSE, 0, '');
                """));
    }

    @Test
    void stopsWhenDuplicateDaysBothContainData() throws Exception {
        DataSource dataSource = legacyDatabase("unsafe");
        execute(dataSource, """
                INSERT INTO training_plans (id) VALUES (1);
                INSERT INTO training_plan_days
                    (id, training_plan_id, weekday, title, description, sort_order, rest_day,
                     estimated_duration_minutes, notes)
                VALUES
                    (10, 1, 'MONDAY', '', '', 1, FALSE, 0, ''),
                    (11, 1, 'MONDAY', '', '', 1, FALSE, 0, '');
                INSERT INTO training_day_exercises (plan_day_id) VALUES (10), (11);
                """);

        IllegalStateException error = assertThrows(
                IllegalStateException.class,
                () -> new TrainingPlanWeekMigration(dataSource).migrate());

        assertTrue(error.getMessage().contains("duplicados com exercícios ou atividades"));
        assertEquals(2, count(dataSource, "SELECT COUNT(*) FROM training_plan_days"));
    }

    private DataSource legacyDatabase(String name) throws SQLException {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:week-" + name + ";DB_CLOSE_DELAY=-1", "sa", "");
        execute(dataSource, """
                CREATE TABLE training_plans (id BIGINT PRIMARY KEY);
                CREATE TABLE training_plan_days (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    training_plan_id BIGINT NOT NULL,
                    weekday VARCHAR(12) NOT NULL,
                    title VARCHAR(120),
                    description VARCHAR(500),
                    sort_order INT NOT NULL,
                    rest_day BOOLEAN NOT NULL,
                    estimated_duration_minutes INT NOT NULL,
                    notes VARCHAR(600)
                );
                CREATE TABLE training_day_exercises (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    plan_day_id BIGINT NOT NULL
                );
                CREATE TABLE rest_day_activities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    plan_day_id BIGINT NOT NULL
                );
                """);
        return dataSource;
    }

    private void execute(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            for (String command : sql.split(";")) {
                if (!command.isBlank()) statement.execute(command);
            }
        }
    }

    private long count(DataSource dataSource, String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             var rows = connection.createStatement().executeQuery(sql)) {
            rows.next();
            return rows.getLong(1);
        }
    }
}
