import { RefreshControl, StyleSheet, Text, View } from 'react-native'
import type { HistoryProgress, WorkoutSession } from '@training/training-domain'
import { EmptyState, InlineNotice, SectionHeader, StatusPill } from '../components/ui'
import { ScreenScrollView } from '../components/Screen'
import { ScreenHeader } from '../components/ScreenHeader'
import { type ThemeColors, useTheme } from '../theme'
import { typography } from '../theme/typography'

const statusLabels = { COMPLETED: 'Concluído', ABANDONED: 'Não concluído', IN_PROGRESS: 'Em andamento', PAUSED: 'Pausado' } as const
export function HistoryScreen({ sessions, progress, loading, warning, onRefresh }: { sessions: WorkoutSession[]; progress: HistoryProgress; loading: boolean; warning?: string; onRefresh: () => void }) { const { colors } = useTheme(); const styles = createStyles(colors); return <ScreenScrollView includeBottomInset={false} refreshControl={<RefreshControl refreshing={loading} onRefresh={onRefresh} tintColor={colors.primary} />}><ScreenHeader eyebrow="Progresso" title="Histórico" description="Seu treino, calculado neste aparelho." variant="standard" />{!!warning && <InlineNotice tone="warning" message={warning} />}<View style={styles.primaryMetrics}><Metric label="SESSÕES" value={progress.completedSessions} /><Metric label="ESTA SEMANA" value={progress.completedThisWeek} /><Metric label="CONCLUSÃO" value={`${progress.completionRate}%`} /></View><Text style={styles.secondaryMetrics}>{Math.round(progress.totalDurationSeconds / 60)} min · {Math.round(progress.totalVolume)} kg de volume · {progress.completedExercises} exercícios</Text><SectionHeader title="SESSÕES RECENTES" />{loading && !sessions.length ? <Text style={styles.loading}>Carregando sessões…</Text> : !sessions.length ? <EmptyState title="Nenhuma sessão registrada" description="Seus treinos concluídos e não concluídos aparecerão aqui." /> : <View style={styles.list}>{sessions.map((session, index) => <SessionRow key={session.id} session={session} divider={index > 0} />)}</View>}</ScreenScrollView> }
function Metric({ label, value }: { label: string; value: string | number }) { const { colors } = useTheme(); const styles = createStyles(colors); return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View> }
function SessionRow({ session, divider }: { session: WorkoutSession; divider: boolean }) { const { colors } = useTheme(); const styles = createStyles(colors); const exercises = session.exercises.map((exercise) => exercise.substituteName ?? exercise.name); return <View accessibilityLabel={`${session.workoutName}, ${statusLabels[session.status]}`} style={[styles.session, divider && styles.divider]}><View style={styles.sessionTop}><Text style={styles.date}>{formatDateKey(session.scheduledDate)}</Text><StatusPill label={statusLabels[session.status]} /></View><Text style={styles.sessionName}>{session.workoutName}</Text><Text style={styles.day}>{session.dayName}</Text><Text style={styles.sessionMeta}>{formatDuration(session.totalDurationSeconds)} · {session.completedSets} séries{session.totalVolume > 0 ? ` · ${Math.round(session.totalVolume)} kg` : ''}</Text><Text numberOfLines={2} style={styles.exercises}>{exercises.slice(0, 3).join(' · ')}{exercises.length > 3 ? ` · +${exercises.length - 3} exercícios` : ''}</Text></View> }
function formatDateKey(value: string) { const today = new Date().toISOString().slice(0, 10); return value === today ? 'Hoje' : value.split('-').reverse().join('/') }
export function formatDuration(seconds: number) { if (seconds < 60) return `${seconds} s`; const minutes = Math.floor(seconds / 60); const remaining = seconds % 60; return remaining ? `${minutes} min ${remaining} s` : `${minutes} min` }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ primaryMetrics: { flexDirection: 'row', gap: 8 }, metric: { backgroundColor: colors.surfaceSecondary, borderRadius: 14, flex: 1, minHeight: 92, padding: 12 }, metricLabel: { ...typography.caption, color: colors.textSecondary, fontWeight: '700', letterSpacing: .7 }, metricValue: { color: colors.textPrimary, fontSize: 24, fontWeight: '700', marginTop: 8 }, secondaryMetrics: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 12 }, list: { backgroundColor: colors.surface, borderRadius: 16, overflow: 'hidden' }, session: { minHeight: 116, padding: 16 }, divider: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth }, sessionTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, date: { ...typography.caption, color: colors.textSecondary, fontWeight: '600' }, sessionName: { ...typography.body, color: colors.textPrimary, fontWeight: '700', marginTop: 8 }, day: { ...typography.bodySmall, color: colors.textSecondary, marginTop: 2 }, sessionMeta: { ...typography.caption, color: colors.textSecondary, marginTop: 8 }, exercises: { ...typography.caption, color: colors.textSecondary, lineHeight: 18, marginTop: 4 }, loading: { ...typography.body, color: colors.textSecondary, minHeight: 100, paddingTop: 20, textAlign: 'center' } })
