import { ScrollView, StyleSheet, Text, View } from 'react-native'
import { ScreenHeader } from '../components/ScreenHeader'
import type { WorkoutSession } from '../features/workout-session/model/workoutSession'
import { shared, type ThemeColors, useTheme } from '../theme'
export function HistoryScreen({ sessions }: { sessions: WorkoutSession[] }) {
  const { colors } = useTheme(); const styles = createStyles(colors)
  const completed = sessions.filter(item => item.status === 'COMPLETED')
  const volume = completed.reduce((sum, item) => sum + item.totalVolume, 0)
  return <ScrollView contentContainerStyle={styles.content}><ScreenHeader eyebrow="Evolução real" title={'Histórico e\nprogresso'} description="Métricas calculadas sobre séries persistidas." /><View style={styles.metrics}><View style={styles.metric}><Text style={styles.label}>SESSÕES</Text><Text style={styles.value}>{completed.length}</Text></View><View style={styles.metric}><Text style={styles.label}>VOLUME</Text><Text style={styles.value}>{volume}kg</Text></View></View>{!sessions.length ? <View style={styles.empty}><Text style={styles.title}>Nenhuma sessão registrada</Text><Text style={styles.meta}>Inicie um treino pela ficha ativa.</Text></View> : sessions.map(item => <View key={item.id} style={styles.card}><View style={[styles.status, item.status === 'COMPLETED' && styles.complete]}><Text style={styles.statusText}>{item.status === 'COMPLETED' ? '✓' : '×'}</Text></View><View style={{ flex: 1 }}><Text style={styles.title}>{item.workoutName}</Text><Text style={styles.meta}>{item.scheduledDate.split('-').reverse().join('/')} · {item.completedSets} séries</Text></View><Text style={styles.volume}>{item.totalVolume}kg</Text></View>)}</ScrollView>
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  content: { padding: shared.pagePadding, paddingBottom: 125 }, metrics: { flexDirection: 'row', gap: 8, marginBottom: 13 }, metric: { backgroundColor: colors.card, borderRadius: 18, flex: 1, padding: 14 }, label: { color: colors.gray400, fontSize: 8 }, value: { color: colors.ink, fontSize: 21, fontWeight: '800', marginTop: 6 }, card: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.gray200, borderRadius: 19, borderWidth: 1, flexDirection: 'row', gap: 11, marginBottom: 8, padding: 11 }, status: { alignItems: 'center', backgroundColor: colors.gray100, borderRadius: 14, height: 44, justifyContent: 'center', width: 44 }, complete: { backgroundColor: '#d1fae5' }, statusText: { color: '#047857', fontWeight: '800' }, title: { color: colors.ink, fontSize: 11, fontWeight: '700' }, meta: { color: colors.gray500, fontSize: 8, marginTop: 4 }, volume: { color: colors.ink, fontSize: 10, fontWeight: '800' }, empty: { alignItems: 'center', minHeight: 260, justifyContent: 'center' },
})
