import { useMemo, useState } from 'react'
import { Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native'
import { FormField } from '../components/FormField'
import { PrimaryButton } from '../components/PrimaryButton'
import { ScreenHeader } from '../components/ScreenHeader'
import type { ExerciseDefinition, ExerciseDefinitionInput } from '../models/training'
import { shared, type ThemeColors, useTheme } from '../theme'

export function LibraryScreen({ exercises, onCreate }: { exercises: ExerciseDefinition[]; onCreate: (payload: ExerciseDefinitionInput) => Promise<boolean> }) {
  const { colors } = useTheme(); const styles = createStyles(colors)
  const [query, setQuery] = useState(''); const [show, setShow] = useState(false)
  const [name, setName] = useState(''); const [muscle, setMuscle] = useState(''); const [equipment, setEquipment] = useState('')
  const filtered = useMemo(() => exercises.filter(item => !item.archived && `${item.name} ${item.primaryMuscleGroup}`.toLowerCase().includes(query.toLowerCase())), [exercises, query])
  async function submit() { if (!name.trim() || !muscle.trim() || !equipment.trim()) return; if (await onCreate({ name, description: '', primaryMuscleGroup: muscle, secondaryMuscleGroups: [], equipment, category: 'STRENGTH', difficulty: 'Iniciante', instructions: '', notes: '', mediaUrl: '', unilateral: false, timed: false })) { setShow(false); setName(''); setMuscle(''); setEquipment('') } }
  return <><ScrollView contentContainerStyle={styles.content}><ScreenHeader eyebrow="Catálogo reutilizável" title={'Biblioteca de\nexercícios'} description="Busque e reutilize movimentos em qualquer ficha." /><TextInput value={query} onChangeText={setQuery} placeholder="Buscar exercício..." placeholderTextColor={colors.gray400} style={styles.search} />{filtered.map(item => <View key={item.id} style={styles.card}><View style={styles.icon}><Text style={styles.iconText}>⌁</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.primaryMuscleGroup} · {item.equipment}</Text></View><Text style={styles.category}>{item.category}</Text></View>)}</ScrollView><TouchableOpacity style={styles.fab} onPress={() => setShow(true)}><Text style={styles.fabText}>＋</Text></TouchableOpacity><Modal visible={show} transparent animationType="slide"><View style={styles.backdrop}><View style={styles.sheet}><Text style={styles.sheetTitle}>Novo exercício</Text><FormField label="Nome" value={name} onChangeText={setName} /><FormField label="Grupo principal" value={muscle} onChangeText={setMuscle} /><FormField label="Equipamento" value={equipment} onChangeText={setEquipment} /><PrimaryButton label="Salvar na biblioteca" onPress={() => void submit()} /><TouchableOpacity onPress={() => setShow(false)}><Text style={styles.cancel}>Cancelar</Text></TouchableOpacity></View></View></Modal></>
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  content: { padding: shared.pagePadding, paddingBottom: 125 }, search: { backgroundColor: colors.card, borderColor: colors.gray200, borderRadius: 16, borderWidth: 1, color: colors.ink, marginBottom: 13, minHeight: 52, paddingHorizontal: 14 },
  card: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.gray200, borderRadius: 19, borderWidth: 1, flexDirection: 'row', gap: 11, marginBottom: 8, padding: 11 }, icon: { alignItems: 'center', backgroundColor: colors.nearBlack, borderRadius: 14, height: 44, justifyContent: 'center', width: 44 }, iconText: { color: '#fff', fontSize: 18 }, name: { color: colors.ink, fontSize: 11, fontWeight: '700' }, meta: { color: colors.gray500, fontSize: 8, marginTop: 4 }, category: { color: colors.gray400, fontSize: 7 },
  fab: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 19, bottom: 94, height: 56, justifyContent: 'center', position: 'absolute', right: 20, width: 56 }, fabText: { color: colors.onPrimary, fontSize: 22 }, backdrop: { backgroundColor: 'rgba(0,0,0,.6)', flex: 1, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.card, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, paddingBottom: 30 }, sheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '700', marginBottom: 20 }, cancel: { color: colors.gray500, fontSize: 11, fontWeight: '700', padding: 15, textAlign: 'center' },
})
